motors:
  - {acceleration: 0.5, function: linear, group: Eyes, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1563, lin_max: -0.342, lin_min: 0.252, max: 1801,
    max1: null, max2: null, min: 1240, motor_id: 8, name: Eyes_Pitch, other_func: null,
    parser: getproperty, parser_param: m_eyeGazeLeftPitch, sort_no: 90, speed: 0.5,
    topic: right}
  - {acceleration: 0.5, function: linear, group: Eyes, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1440, lin_max: 0.38, lin_min: -0.49, max: 1643, max1: null,
    max2: null, min: 1164, motor_id: 0, name: Eye_R, other_func: null, parser: getproperty,
    parser_param: m_eyeGazeRightYaw, sort_no: 70, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: weightedsum, group: Eyes, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1576, lin_max: null, lin_min: null, max: 1762, max1: 0.6,
    max2: 1, min: 1345, motor_id: 1, name: Eyelid_U_R, other_func: null, parser: fsshapekey,
    parser_param: eye-blink.UP.R;eye-flare.UP.R, sort_no: 50, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: weightedsum, group: Eyes, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1609, lin_max: null, lin_min: null, max: 1788, max1: 1,
    max2: 1, min: 1358, motor_id: 2, name: EyeLid_L_R, other_func: null, parser: fsshapekey,
    parser_param: eye-flare.LO.R;eye-blink.LO.R, sort_no: 100, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: null, group: Jaw, hardware: pololu, imax1: null, imax2: null,
    imin: null, init: 825, lin_max: null, lin_min: null, max: 1120, max1: null, max2: null,
    min: 820, motor_id: 3, name: Jaw_Forward_R, other_func: null, parser: null, parser_param: null,
    sort_no: 280, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: weightedsum, group: Lips, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1343, lin_max: null, lin_min: null, max: 1800, max1: -0.3,
    max2: 0.8, min: 1263, motor_id: 15, name: Lower_Lip_C, other_func: null, parser: fsshapekey,
    parser_param: lip.DN.C;lip.DN.C, sort_no: 230, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: null, group: Lips, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1840, lin_max: null, lin_min: null, max: 2125, max1: null,
    max2: null, min: 1530, motor_id: 14, name: Lower_Lip_Roll_C, other_func: null, parser: null,
    parser_param: null, sort_no: 240, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: weightedsum, group: Lips, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1500, lin_max: null, lin_min: null, max: 2100, max1: 0.4,
    max2: -0.3, min: 1116, motor_id: 4, name: Lower_Lip_R, other_func: null, parser: fsshapekey,
    parser_param: lip.DN.R;lip.DN.R, sort_no: 210, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: null, group: Lips, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1500, lin_max: null, lin_min: null, max: 2025, max1: null,
    max2: null, min: 870, motor_id: 5, name: Lower_Lip_Roll_R, other_func: null, parser: null,
    parser_param: null, sort_no: 220, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: null, group: Lips, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1270, lin_max: null, lin_min: null, max: 1600, max1: null,
    max2: null, min: 900, motor_id: 10, name: Lip_Upper_R, other_func: null, parser: null,
    parser_param: null, sort_no: 140, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: linear, group: Eyes, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1620, lin_max: 0, lin_min: 1, max: 1637, max1: null,
    max2: null, min: 1270, motor_id: 12, name: Sneer_L, other_func: null, parser: fsshapekey,
    parser_param: sneer.L, sort_no: 130, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: null, group: Lips, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1550, lin_max: null, lin_min: null, max: 2175, max1: null,
    max2: null, min: 1370, motor_id: 13, name: Upper_Lip_Forward, other_func: null,
    parser: null, parser_param: null, sort_no: 160, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: null, group: Lips, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1800, lin_max: null, lin_min: null, max: 2175, max1: null,
    max2: null, min: 1190, motor_id: 14, name: Lower_Lip_Forward, other_func: null,
    parser: null, parser_param: null, sort_no: 250, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: weightedsum, group: Brows, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1345, lin_max: null, lin_min: null, max: 1768, max1: 1,
    max2: 1, min: 820, motor_id: 9, name: Brow_Outer_R, other_func: null, parser: fsshapekey,
    parser_param: brow_outer_UP.R;brow_outer_DN.R, sort_no: 10, speed: 0.5, topic: right}
  - {acceleration: 0.5, function: linear, group: Jaw, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1570, lin_max: 1, lin_min: 0, max: 2085, max1: null,
    max2: null, min: 1520, motor_id: 2, name: Jaw_open, other_func: null, parser: fsshapekey,
    parser_param: jaw, sort_no: 290, speed: 0.5, topic: middle}
  - {acceleration: 0.5, function: weightedsum, group: Lips, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1430, lin_max: null, lin_min: null, max: 2175, max1: 0.8,
    max2: 0.6, min: 1000, motor_id: 3, name: Smile_R, other_func: null, parser: fsshapekey,
    parser_param: lips-smile.R;lips-frown.R, sort_no: 170, speed: 0.5, topic: middle}
  - {acceleration: 0.5, function: weightedsum, group: Brows, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1600, lin_max: null, lin_min: null, max: 2175, max1: 1,
    max2: 1, min: 1023, motor_id: 4, name: Inner_Brow_R_UD, other_func: null, parser: fsshapekey,
    parser_param: brow_inner_DN.R;brow_inner_UP.R, sort_no: 20, speed: 0.5, topic: middle}
  - {acceleration: 0.5, function: weightedsum, group: Brows, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1380, lin_max: null, lin_min: null, max: 2100, max1: 1,
    max2: 1, min: 820, motor_id: 1, name: Brow_Inner_L, other_func: null, parser: fsshapekey,
    parser_param: brow_inner_UP.L;brow_inner_DN.L, sort_no: 30, speed: 0.5, topic: middle}
  - {acceleration: 0.5, function: weightedsum, group: Lips, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1888, lin_max: null, lin_min: null, max: 2175, max1: 0.8,
    max2: 0.6, min: 1188, motor_id: 0, name: Smile_L, other_func: null, parser: fsshapekey,
    parser_param: lips-frown.L;lips-smile.L, sort_no: 180, speed: 0.5, topic: middle}
  - {acceleration: 0.5, function: linear, group: Eyes, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1578, lin_max: 0.38, lin_min: -0.49, max: 1743, max1: null,
    max2: null, min: 1384, motor_id: 0, name: Eye_L, other_func: null, parser: getproperty,
    parser_param: m_eyeGazeLeftYaw, sort_no: 80, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: weightedsum, group: Eyes, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1355, lin_max: null, lin_min: null, max: 1636, max1: 1,
    max2: 0.6, min: 1166, motor_id: 1, name: EyeLid_U_L, other_func: null, parser: fsshapekey,
    parser_param: eye-flare.UP.L;eye-blink.UP.L, sort_no: 60, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: weightedsum, group: Eyes, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1510, lin_max: null, lin_min: null, max: 1665, max1: 1,
    max2: 1, min: 1331, motor_id: 2, name: EyeLid_L_L, other_func: null, parser: fsshapekey,
    parser_param: eye-blink.LO.L;eye-flare.LO.L, sort_no: 110, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: null, group: Jaw, hardware: pololu, imax1: null, imax2: null,
    imin: null, init: 1500, lin_max: null, lin_min: null, max: 1848, max1: null, max2: null,
    min: 1103, motor_id: 3, name: Jaw_Forward_L, other_func: null, parser: null, parser_param: null,
    sort_no: 300, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: linear, group: Lips, hardware: pololu, imax1: 0, imax2: 1,
    imin: null, init: 1750, lin_max: 0.3, lin_min: 0, max: 2160, max1: 1, max2: 1, min: 1500,
    motor_id: 4, name: Lower_lip_L, other_func: null, parser: fsshapekey, parser_param: lip.DN.L,
    sort_no: 260, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: null, group: Lips, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1800, lin_max: null, lin_min: null, max: 2180, max1: null,
    max2: null, min: 1500, motor_id: 5, name: Lower_Lip_Roll_L, other_func: null, parser: null,
    parser_param: null, sort_no: 270, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: weightedsum, group: Lips, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1633, lin_max: null, lin_min: null, max: 1968, max1: -0.5,
    max2: 1, min: 1182, motor_id: 6, name: Lip_Upper_L, other_func: null, parser: fsshapekey,
    parser_param: lip.UP.L;lip.UP.L, sort_no: 160, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: linear, group: Eyes, hardware: pololu, imax1: 0, imax2: 1,
    imin: null, init: 1692, lin_max: 1, lin_min: 0, max: 2175, max1: 1, max2: 1, min: 1688,
    motor_id: 7, name: Sneer_R, other_func: null, parser: fsshapekey, parser_param: sneer.R,
    sort_no: 120, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: linear, group: Lips, hardware: pololu, imax1: 0, imax2: 1,
    imin: null, init: 1650, lin_max: 0.6, lin_min: 0, max: 2175, max1: 1, max2: 1, min: 1600,
    motor_id: 8, name: Smile2_L, other_func: null, parser: fsshapekey, parser_param: lips-smile.L,
    sort_no: 190, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: weightedsum, group: Lips, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1428, lin_max: null, lin_min: null, max: 1838, max1: -0.5,
    max2: 1, min: 820, motor_id: 17, name: Lip_Upper_C, other_func: null, parser: fsshapekey,
    parser_param: lip-UP.C;lip-UP.C, sort_no: 150, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: weightedsum, group: Brows, hardware: pololu, imax1: 0,
    imax2: 1, imin: null, init: 1011, lin_max: null, lin_min: null, max: 1650, max1: 1,
    max2: 1, min: 820, motor_id: 14, name: Outer_Brow_L, other_func: null, parser: fsshapekey,
    parser_param: brow_outer_DN.L;brow_outer_UP.L, sort_no: 40, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: null, group: Lips, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1250, lin_max: null, lin_min: null, max: 2175, max1: null,
    max2: null, min: 1210, motor_id: 22, name: Frown_R, other_func: null, parser: null,
    parser_param: null, sort_no: 200, speed: 0.5, topic: left}
  - {acceleration: 0.5, function: null, group: Brows, hardware: pololu, imax1: null,
    imax2: null, imin: null, init: 1100, lin_max: null, lin_min: null, max: 2150, max1: null,
    max2: null, min: 1093, motor_id: 23, name: Inner_Bwow_L, other_func: null, parser: null,
    parser_param: null, sort_no: 35, speed: 0.5, topic: left}
  - {acceleration: 10, function: null, group: Neck, hardware: dynamixel, imax1: null,
    imax2: null, imin: null, init: 3026, lin_max: null, lin_min: null, max: 3416, max1: null,
    max2: null, min: 2635, motor_id: 3, name: Right_Neck, other_func: '[{"name":"quaternion2euler","axis":"x"},{"name":"linear","scale":1.3,"translate":0}]',
    parser: getproperty, parser_param: m_headRotation, sort_no: 310, speed: 1, topic: null}
  - {acceleration: 10, function: null, group: Neck, hardware: dynamixel, imax1: null,
    imax2: null, imin: null, init: 2178, lin_max: null, lin_min: null, max: 2568, max1: null,
    max2: null, min: 1787, motor_id: 4, name: Left_Neck, other_func: '[{"name":"quaternion2euler","axis":"x"},{"name":"linear","scale":-1.3,"translate":0}]',
    parser: getproperty, parser_param: m_headRotation, sort_no: 320, speed: 1, topic: null}
  - {acceleration: 20, function: null, group: Neck, hardware: dynamixel, imax1: null,
    imax2: null, imin: null, init: 2000, lin_max: null, lin_min: null, max: 2730, max1: null,
    max2: null, min: 1370, motor_id: 0, name: Yaw, other_func: '[{"name":"quaternion2euler","axis":"z"},{"name":"linear","scale":-2,"translate":0}]',
    parser: getproperty, parser_param: m_headRotation, sort_no: 330, speed: 1, topic: null}
  - {acceleration: 10, function: null, group: Neck, hardware: dynamixel, imax1: null,
    imax2: null, imin: null, init: 1647, lin_max: null, lin_min: null, max: 2219, max1: null,
    max2: null, min: 1304, motor_id: 1, name: Right_Base, other_func: '[{"name":"quaternion2euler","axis":"x"},{"name":"linear","scale":1.3,"translate":0}]',
    parser: getproperty, parser_param: m_headRotation, sort_no: 340, speed: 1, topic: null}
  - {acceleration: 10, function: null, group: Neck, hardware: dynamixel, imax1: null,
    imax2: null, imin: null, init: 2173, lin_max: null, lin_min: null, max: 2514, max1: null,
    max2: null, min: 1509, motor_id: 2, name: Left_Base, other_func: '[{"name":"quaternion2euler","axis":"x"},{"name":"linear","scale":-1.3,"translate":0}]',
    parser: getproperty, parser_param: m_headRotation, sort_no: 350, speed: 1, topic: null}
